#!/bin/sh

 #######################################
 # BEGINOF b(j)=b(j)+a(ixx)/PARAMETERS #
 #######################################

 # Size if the smallest vector in the measurement.
 START=1000
 
 # Change of size in every STEP.
 INCREMENT=2
 
 # Number of STEPS that are made = number of measurements.
 # => biggest vector has size of:
 #    VECADD_START+VECADD_INCREMENT*VECADD_STEPS
 STEPS=600
 
 # Number of repetitions for every single measurement in
 # the kernel.
 # This multiplies with the ACCURACY-variable in the
 # configure script of the benchit main program.
 PRECISION=1

 #######################################
 # ENDOF b(j)=b(j)+a(ixx)/PARAMETERS #
 #######################################
