#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# Last change by: $Author: hackenb $
# $Revision: 1.1 $
# $Date: 2007/01/22 14:54:19 $
#####################################################################

 # Define the lower and upper bound for your problemsize.
 # For large problemsizes you might have to increase MPI_GROUP_MAX
 # and/or MPI_MSGS_MAX on your system
 BENCHIT_KERNEL_PROBLEMSIZE_MIN=1024
 BENCHIT_KERNEL_PROBLEMSIZE_MAX=20000
 BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT=21

 # Describe your own kernel modifications
 #BENCHIT_KERNEL_COMMENT="128 Cores"

# Parameters for run_benchit; uncomment and change the ones you need
# accuracy
#BENCHIT_RUN_ACCURACY=2
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=8
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=


#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.1  2007/01/22 14:54:19  hackenb
# + initial commit :-)
#
#
#####################################################################
