#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: jmuelle $
# $Revision: 1.7 $
# $Date: 2007/07/06 14:54:08 $
#####################################################################

 # Iterate over matrix size from BENCHIT_KERNEL_PROBLEMSIZE_MIN
 # to BENCHIT_KERNEL_PROBLEMSIZE_MAX, incrementing by
 # BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT with each step.

 BENCHIT_KERNEL_PROBLEMSIZE_MIN=1
 BENCHIT_KERNEL_PROBLEMSIZE_MAX=1200
 BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT=2

 # Describe your own kernel modifications
 #BENCHIT_KERNEL_COMMENT=""

# Parameters for run_benchit; uncomment and change the ones you need
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=1
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=


###############################################################################
#  Log-History
#
#  $Log: PARAMETERS,v $
#  Revision 1.7  2007/07/06 14:54:08  jmuelle
#  Adjusted PARAMETERS to reasonable values
#
#  Revision 1.6  2006/05/10 20:41:22  hackenb
#  implemented new iterating strategy
#
#  Revision 1.5  2006/05/09 10:26:17  hackenb
#  *** empty log message ***
#
#  Revision 1.4  2005/08/30 22:24:00  mickler
#  + CHANGED: shell variable BENCHIT_KERNEL_NAME_STRING renamed to
#    BENCHIT_KERNELNAME and made necessary changes in COMPILE.SHs and
#    main BenchIT files (benchit.c, JBI.java, ...)
#  - FIXED: user settings for e.g. linear measurement were not used,
#    added the ${BENCHIT_DEFINES} to the compile commands in COMPILE.SHs
#
#  Revision 1.3  2005/07/29 11:53:51  wloch
#  removed setting of kernelname in bi getinfo and equalized parameter variables
#
#  Revision 1.2  2005/07/19 12:10:36  wloch
#  added cvs footers
#
###############################################################################
