#! /bin/bash

VAR_NAME=$1

if [ ${1} -z ] || [ ${1} = "--help" ] || [ ${1} = "-h" ]
	then echo "./var_help VAR_NAME"
	exit 0
fi

BEGIN_NAME="<BEGIN ${VAR_NAME}>"
END_NAME="<END ${VAR_NAME}>"

BEGIN_LINE=`cat variables.txt | grep -n "${BEGIN_NAME}" | cut -d : -f 1`

END_LINE=`cat variables.txt | grep -n "${END_NAME}" | cut -d : -f 1`

END_LINE=$(( END_LINE-1 ))

NUMBER_OF_LINES=$(( ${END_LINE}-${BEGIN_LINE} ))

cat variables.txt | head -n ${END_LINE} | tail -n ${NUMBER_OF_LINES}
