#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: william $
# $Revision: 1.1 $
# $Date: 2006/12/14 12:54:15 $
#####################################################################

 #########################
 # number of IO-Channels #
 #########################
 export BENCHIT_KERNEL_NUMCHANNELS="1"

 #######################################
 # path for files that will be written #
 #######################################
 export BENCHIT_KERNEL_DISKPATH="/var/tmp/"

 ######################################################
 # diskspace for files that will be written (in byte) #
 ######################################################
# export BENCHIT_KERNEL_DISKSPACE="104857600.0"  # 100Mb
 export BENCHIT_KERNEL_DISKSPACE="524288000.0"  # 500Mb

 ###################################################
 # RAM that is installed on the computer (in byte) #
 ###################################################
 #export BENCHIT_KERNEL_RAMSIZE="134217728.0"   #128Mb

 #######################
 # threads per channel #
 #######################
 export BENCHIT_KERNEL_CHANNELFACTOR="1"

 #########################################
 # size in Bytes (one file)		 #
 # - has to be at least 1048576.0 = 1 Mb #
 # - should be a multiple of 1048576.0	 #
 #########################################
 export BENCHIT_KERNEL_FILESIZE="5242880.0"   #5Mb

# Parameters for run_benchit; uncomment and change the ones you need
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=1
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=

#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.1  2006/12/14 12:54:15  william
# changed the algorithm a bit for mor informative resultfilesmade chenges to reflect new format of COMPILE.SH and a like
#
# Revision 1.2  2006/04/27 12:01:16  william
# altered, cleaned up and successfully tested the kernel
#
#
#####################################################################
