#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: hackenb $
# $Revision: 1.2 $
# $Date: 2006/01/03 18:10:34 $
#####################################################################

 # BENCHIT_KERNEL_MIN_ACCESS_SIZE is the minimum  
 # of accessed memory (in KByte)      
 BENCHIT_KERNEL_MIN_ACCESS_SIZE=2

 # BENCHIT_KERNEL_MAX_ACCESS_SIZE is the maximum 
 # of accessed memory (in KByte)     
 BENCHIT_KERNEL_MAX_ACCESS_SIZE=10240

 # BENCHIT_KERNEL_ACCESS_STRIDE is the stride in KByte between 
 # two measurement points                       
 BENCHIT_KERNEL_ACCESS_STRIDE=10
 
 
# Describe your own kernel modifications
#BENCHIT_KERNEL_COMMENT=""

# Parameters for run_benchit; uncomment and change the ones you need
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=4
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=


#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.2  2006/01/03 18:10:34  hackenb
# modified/unified header and footer
# new interface
# now using bi_gettime()
#
#
#####################################################################
