#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: hackenb $
# $Revision: 1.3 $
# $Date: 2006/01/03 16:37:29 $
#####################################################################

 # BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MIN is the minimum
 # of accessed memory (in MByte)                    
 BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MIN=0.005

 # BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MAX is the maximum
 # of accessed memory (in MByte)                     
 BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MAX=50

 # BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MEASUREMENTS
 # is the number of measurements              
 BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_MEASUREMENTS=100

 # BENCHIT_KERNEL_MEM_READ_POINTS are explicite sizes of memory to be measured.
 # it overrides the variables above                                      
 #BENCHIT_KERNEL_MEM_READ_POINTS=0.00048828125,0.0009765625,0.001953125,0.00390625,0.0078125,0.015625,0.03125,0.0625,0.125,0.25,0.5,1,2,4,8,16,32,64,128,256

 # BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_STRIDES are the strides
 # to access the memory                                   
 BENCHIT_KERNEL_MEMORYLATENCIES_C_READ_STRIDES=1,4,16,32,64,128

# Describe your own kernel modifications
#BENCHIT_KERNEL_COMMENT=""

# Parameters for run_benchit; uncomment and change the ones you need
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=1
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=
 

#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.3  2006/01/03 16:37:29  hackenb
# modified/unified header and footer
# new interface
#
#
#####################################################################
