#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: william $
# $Revision: 1.1 $
# $Date: 2006/11/01 20:22:51 $
#####################################################################
 
 # Where the root directory shall be written
 BENCHIT_KERNEL_IO_TREE_ROOT="/tmp/benchit_io_dir"

 # Depth of binary directory tree
 BENCHIT_KERNEL_IO_TREE_DEPTH=5
 
 # |F|iles |P|er |D|irectory, only for leafs
 BENCHIT_KERNEL_IO_TREE_FPD=2
 
 # How many directories to read in each measurement
 BENCHIT_KERNEL_IO_DIRS_TO_READ=10

 # Describe your own kernel modifications
 #BENCHIT_KERNEL_COMMENT=""

# Parameters for run_benchit; uncomment and change the ones you need
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=1
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=


#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.1  2006/11/01 20:22:51  william
# first checkin after complete codereview and simple tests
#
# Revision 1.1.1.1  2006/04/18 10:03:49  william
# import version 0.1
#
# Revision 1.5  2006/01/09 15:57:01  william
# cvs-keyword-problems
#
#
#####################################################################
