#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: jmuelle $
# $Revision: 1.2 $
# $Date: 2007/07/06 14:54:08 $
#####################################################################

 BENCHIT_KERNEL_PROBLEMSIZE_MIN=1
 BENCHIT_KERNEL_PROBLEMSIZE_MAX=1200
 BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT=2

#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.2  2007/07/06 14:54:08  jmuelle
# Adjusted PARAMETERS to reasonable values
#
# Revision 1.1  2006/04/24 11:16:11  rschoene
# initial commit for matmul-f77-int (mostly taken from matmul-f77-double)
#
#
#####################################################################
