#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: developer@benchit.org
#
# Last change by: $Author: rschoene $
# $Revision: 1.1 $
# $Date: 2007/02/13 12:43:18 $
#####################################################################

 # BENCHIT_KERNEL_MIN_ACCESS_LENGTH is the minimum length of the double fields
 BENCHIT_KERNEL_MIN_ACCESS_LENGTH=100

 # BENCHIT_KERNEL_MAX_ACCESS_LENGTH is the maximum length of the double fields
 BENCHIT_KERNEL_MAX_ACCESS_LENGTH=10000000

 # BENCHIT_KERNEL_ACCESS_STEPS is the number of measurement points
 BENCHIT_KERNEL_ACCESS_STEPS=500
 
 # BENCHIT_KERNEL_INTERNAL_NUM_MEASUREMENT defines how often the kernel is
 # repeated internally (must be >=1) this is multiplied with BENCHIT_ACCURACY
 # represents "NTIMES" from original STREAM
 BENCHIT_KERNEL_INTERNAL_NUM_MEASUREMENT=10
 
 # BENCHIT_KERNEL_OFFSET defines the offset(an additional length of the vectors)
 # represents "OFFSET" from original STREAM
 BENCHIT_KERNEL_OFFSET=0
 
 # Parameters for run_benchit; uncomment and change the ones you need
 # maximum memory for processes in kB
 #BENCHIT_RUN_MEMORY=1024
 # number of processors
 # BENCHIT_NUM_CPUS=1
 # set core file size limit in kB
 #BENCHIT_RUN_CORESIZE=1024
 # print all output to file
 #BENCHIT_RUN_OUTPUTFILE=output.txt
 # remove executable after run, if 1
 #BENCHIT_RUN_CLEAN=0
 # do not execute anything, just print out comments
 #BENCHIT_RUN_TEST="1"
 # timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
 #BENCHIT_RUN_QUEUETIMELIMIT=


#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.1  2007/02/13 12:43:18  rschoene
# STREAM-Benchmark in C
#
#
#####################################################################
