#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: rschoene $
# $Revision: 1.2 $
# $Date: 2006/04/10 08:24:12 $
#####################################################################

 # Iterate over matrix size from BENCHIT_DGEMV_C_SSE2_UNALIGN_MIN
 # to BENCHIT_DGEMV_C_SSE2_UNALIGN_MAX, incrementing by
 # BENCHIT_DGEMV_C_SSE2_UNALIGN_INCREMENT with each step.
 BENCHIT_DGEMV_C_SSE2_UNALIGN_MIN=1
 BENCHIT_DGEMV_C_SSE2_UNALIGN_INCREMENT=1
 BENCHIT_DGEMV_C_SSE2_UNALIGN_MAX=300

 # Describe your own kernel modifications
 #BENCHIT_KERNEL_COMMENT=""

# Parameters for run_benchit; uncomment and change the ones you need
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=1
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=

###############################################################################
#  Log-History
#
#  $Log: PARAMETERS,v $
#  Revision 1.2  2006/04/10 08:24:12  rschoene
#  changed header/footer
#
#  Revision 1.1  2006/04/05 07:24:49  rschoene
#  gemv, double precision sse2 unaligned
#
###############################################################################
