#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: rschoene $
# $Revision: 1.4 $
# $Date: 2006/10/10 14:58:25 $
#####################################################################

 BENCHIT_KERNEL_RANDOMACCESS_MEMSIZE=1048576
 BENCHIT_KERNEL_RANDOMACCESS_MEASUREMENTS=1000
 
# Describe your own kernel modifications
#BENCHIT_KERNEL_COMMENT=""

# Parameters for run_benchit; uncomment and change the ones you need
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=4
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=


#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.4  2006/10/10 14:58:25  rschoene
# changed defines to environment-variables to use bi_getenv, also new: number
# of measurements
#
# Revision 1.3  2006/01/03 18:25:08  hackenb
# modified/unified header and footer
# new interface
# now using bi_gettime()
#
#
#####################################################################
