#!/bin/sh
######################################################################
#
# B e n c h I T - Performance Measurement for Scientific Applications
#
#  <>
#
#  Author: Robert Wloch (wloch@zhr.tu-dresden.de)
#
#  Last change by $Author: mickler $
#
#  $Revision: 1.3 $
#
#  $Date: 2005/08/30 22:24:01 $
#
######################################################################

######################################################################
# the following lines are for the benchit-shell B-CARE
#
#!BENCHIT_VARIABLE BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_START 1
#!BENCHIT_VARIABLE BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_INCREMENT 1
#!BENCHIT_VARIABLE BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_STEPS 600
######################################################################

 ######################################
 # BEGINOF skeleton_java_pcl/PARAMETERS #
 ######################################

 BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_START=1
 BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_INCREMENT=1
 BENCHIT_SKELETONS_SKELETON_JAVA_0_PCL_0_STEPS=600
 # Parameters for run_benchit; uncomment and change the ones you need
 # maximum memory for processes in kB
 #RUN_MEMORY=1024
 # number of processors
 #NUMCPUS=1
 # allocate number of processors; only required if different from NUMCPUS
 #RUN_ALLOCATE=1
 # set core file size limit in kB
 #RUN_CORESIZE=1024
 # print all output to file
 #RUN_OUTFILE=output.txt
 # remove executable after run, if 1
 #RUN_CLEAN=0
 # use mpirun or mpprun or similar calls to start MPI program
 #RUN_USEMPI="1"
 # run with OpenMP
 #RUN_OMP="1"
 # run Java code - not implemented yet
 #RUN_JAVA="1"
 # do not execute anything, just print out comments
 #RUN_TEST="1"
 # timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
 #RUN_QUEUETIMELIMIT=

 ####################################
 # ENDOF skeleton_java_pcl/PARAMETERS #
 ####################################
