#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: jmuelle $
# $Revision: 1.2 $
# $Date: 2007/07/06 14:54:08 $
#####################################################################
 
 # Iterate over matrix size from BENCHIT_KERNEL_PROBLEMSIZE_MIN
 # to BENCHIT_KERNEL_PROBLEMSIZE_MAX, incrementing by
 # BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT with each step.

 BENCHIT_KERNEL_PROBLEMSIZE_MIN=1
 BENCHIT_KERNEL_PROBLEMSIZE_MAX=10000
 BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT=10
 BENCHIT_KERNEL_LIST="1000-2000/100"
 # explicit name each entry in list or
 # in a from-to/setpsize manner
 # examples:
 # "10, 100, 1000, 10000, 100000, 1000000, 10000000"
 # "100-200, 1000-2000/10, 10000-20000/100"
 # "1000, 2000, 4000, 8000, 16000, 32000, 64000, 128000, 256000, 512000, 1024000, 2048000, 4096000, 8192000"
 

 # Describe your own kernel modifications
 #BENCHIT_KERNEL_COMMENT=""

# Parameters for run_benchit; uncomment and change the ones you need
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=1
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=


#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.2  2007/07/06 14:54:08  jmuelle
# Adjusted PARAMETERS to reasonable values
#
# Revision 1.1  2006/07/24 16:19:11  william
# wrote, tested and submitted 4 different heapsort-versions
#
# Revision 1.5  2006/01/09 15:57:01  william
# cvs-keyword-problems
#
#
#####################################################################
