#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: hackenb $
# $Revision: 1.8 $
# $Date: 2005/12/15 15:44:17 $
#####################################################################

 BENCHIT_KERNEL_PROBLEMSIZE_MIN=1
 BENCHIT_KERNEL_PROBLEMSIZE_MAX=600
 BENCHIT_KERNEL_PROBLEMSIZE_INCREMENT=1

 # Parameters for run_benchit; uncomment and change the ones you need
 # maximum memory for processes in kB
 #BENCHIT_RUN_MEMORY=1024
 # number of processors
 #BENCHIT_NUM_CPUS=1
 # set core file size limit in kB
 #BENCHIT_RUN_CORESIZE=1024
 # print all output to file
 #BENCHIT_RUN_OUTPUTFILE=output.txt
 # remove executable after run, if 1
 #BENCHIT_RUN_CLEAN=0
 # do not execute anything, just print out comments
 #BENCHIT_RUN_TEST="1"
 # timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
 #BENCHIT_RUN_QUEUETIMELIMIT=


#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.8  2005/12/15 15:44:17  hackenb
# modified/unified header and footer
#
#
#####################################################################
