#!/bin/sh
#####################################################################
# BenchIT - Performance Measurement for Scientific Applications
# Contact: benchit@zih.tu-dresden.de
#
# Last change by: $Author: jmuelle $
# $Revision: 1.4 $
# $Date: 2007/07/06 14:54:08 $
#####################################################################

 # how many times should the pingponng be repeated per problemsize
 # usefull with small messages to reduce impact of overhead
 # usually to be left at 1 => only one pingpong
 BENCHIT_KERNEL_REPETITIONS=1
 
 # 1 .. average bandwith for every pair will be presented
 # 0 .. no curve for pair-bandwith
 BENCHIT_KERNEL_SHOW_PAIR_BANDWITH=1
 
 # 1 .. 	aggregated Bandwith of all pairs will be shown
 # 0 .. 	total bandwith will not be shown
 BENCHIT_KERNEL_SHOW_TOTAL_BANDWITH=0
  
 # minimal MessageSize in bytes
 # (1024*1024*1) .. 1 megabyte
 BENCHIT_KERNEL_MIN_MSG_SIZE=$((1024*1))
 
 # maximal Messagesize in bytes
 # (1024*1024*1024) .. 1 gigabyte
 BENCHIT_KERNEL_MAX_MSG_SIZE=$((1024*1024))
 
 # diference of two measurementpoints in size
 # (1024*1024*1) .. 1 megabyte
 # this means you make a measrumant every 1 megabyte from MIN_MSG_SIZE
 # to MAX_MSG_SIZE
 BENCHIT_KERNEL_MSG_SIZE_INCREMENT=$((1024*1))
 
 # commaseparated list of MPI_Comm_rank numbers
 # number of senders must equal number of receivers
 # number of senders+receivers must equal the number of MPI-processes 
 # first entry in sender will build a pair with first entry in receiver
 # second with second and so on
 # if Lists are empty:
 # 						first half of COMM_WORLD => sender
 #						second half => receiver
 #BENCHIT_KERNEL_SENDERLIST="0,2"
 #BENCHIT_KERNEL_RECEIVERLIST="1,3"
 BENCHIT_KERNEL_SENDERLIST=""
 BENCHIT_KERNEL_RECEIVERLIST=""

 # Describe your own kernel modifications
 #BENCHIT_KERNEL_COMMENT=""

# Parameters for run_benchit; uncomment and change the ones you need
#BENCHIT_DEBUGLEVEL=0
# maximum memory for processes in MB
#BENCHIT_RUN_MAX_MEMORY=1024
# number of processors
#BENCHIT_NUM_CPUS=4
# redirect stdout and stderr to file
#BENCHIT_RUN_REDIRECT_CONSOLE=output.txt
# remove executable after run, if 1
#BENCHIT_RUN_CLEAN=1
# do not execute anything, just print out comments
#BENCHIT_RUN_TEST=1
# timelimit used for enqueueing the job; this is NOT BENCHIT_TOTAL_TIMELIMIT
#BENCHIT_RUN_QUEUETIMELIMIT=


#####################################################################
# Log-History
#
# $Log: PARAMETERS,v $
# Revision 1.4  2007/07/06 14:54:08  jmuelle
# Adjusted PARAMETERS to reasonable values
#
# Revision 1.3  2006/01/13 10:24:58  william
# first test successfully completed - minor fixes
#
# Revision 1.3  2006/01/09 15:54:09  william
# cvs-keyword-problems
#
#
#####################################################################
